/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as JokesImport } from './routes/jokes'
import { Route as BabaiImport } from './routes/Babai'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const JokesRoute = JokesImport.update({
  path: '/jokes',
  getParentRoute: () => rootRoute,
} as any)

const BabaiRoute = BabaiImport.update({
  path: '/Babai',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Babai': {
      id: '/Babai'
      path: '/Babai'
      fullPath: '/Babai'
      preLoaderRoute: typeof BabaiImport
      parentRoute: typeof rootRoute
    }
    '/jokes': {
      id: '/jokes'
      path: '/jokes'
      fullPath: '/jokes'
      preLoaderRoute: typeof JokesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  BabaiRoute,
  JokesRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Babai",
        "/jokes"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/Babai": {
      "filePath": "Babai.jsx"
    },
    "/jokes": {
      "filePath": "jokes.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
